name: Deploy Dev

on:
  push:
    branches:
      - 'development'
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    env:
      IMAGE_NAME: us-docker.pkg.dev/${{ secrets.GCP_DEV_PROJECT_ID }}/metrics-service-api/metrics-service-api:latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3

    - name: Login
      uses: google-github-actions/auth@v0
      with:
        credentials_json: ${{ secrets.GCP_DEV_CREDENTIALS }}

    - name: Configure Docker
      run: |
        echo "$KEYS_FILE" | docker login -u _json_key --password-stdin https://us-docker.pkg.dev
      shell: bash
      env:
        KEYS_FILE: ${{ secrets.GCP_DEV_CREDENTIALS }}

    - name: Build Docker Image
      run: docker build . -t "$IMAGE_NAME"

    - name: Push Docker Image
      run: docker push "$IMAGE_NAME"

    - name: Deploy Docker Image
      run: |
        gcloud run deploy metrics-service-api --image="$IMAGE_NAME" --platform=managed --region=us-central1 --project="${{ secrets.GCP_DEV_PROJECT_ID }}"
        gcloud run services update-traffic metrics-service-api --to-latest --region=us-central1
